site_name: Auto3t Docs
nav:
  - Home: index.md
  - 'Getting Started': getting-started.md
  - 'Installation':
    - 'Docker Compose (Default)': 'installation/docker-compose.md'
    - 'Environment variables': 'installation/env-vars.md'
  - 'TV Shows':
    - 'Introduction': 'tv/introduction.md'
    - 'Add new Show': 'tv/add.md'
    - 'Show Detail Page': 'tv/show-detail.md'
    - 'Episode Detail Page': 'tv/episode-detail.md'
  - Movie:
    - 'Introduction': 'movie/introduction.md'
    - 'Add new Movie': 'movie/add.md'
    - 'Movie Detail Page': 'movie/movie-detail.md'
  - Collection:
    - 'Introduction': 'collection/introduction.md'
    - 'Add new Collection': 'collection/add.md'
    - 'Collection Detail Page': 'collection/collection-detail.md'
  - People:
    - 'Introduction': 'people/introduction.md'
    - 'Add new Person': 'people/add.md'
    - 'People detail Page': 'people/people-detail.md'
  - Settings:
    - 'Key Words': 'settings/search-keywords.md'
    - 'Movie Release': 'settings/movie-release.md'
    - 'Archive Options': 'settings/archive-options.md'
    - 'Tasks': 'settings/tasks.md'
theme:
  name: material
